In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from ai.datamodules.text import TextDataModule
from ai.constants import REPO_DIR
from ai.models.nlp.transformer import Transformer
from ai.models.nlp.transformer3 import Transformer as Transformer2
from ai.misc_utils import get_vocab_size

/static/user/spock/.cache/pypoetry/virtualenvs/ai-iwSNfyWa-py3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
fname = f'{REPO_DIR}/data/shakespeare.txt'
vocab_size = get_vocab_size(fname)
block_size = 256
batch_size = 2
n_embd = 32

dm = TextDataModule.Config(fname=fname, block_size=block_size, batch_size=batch_size, num_workers=0).i()

In [4]:
# c = c1 = Transformer.Config(vocab_size=vocab_size, n_embd=n_embd, n_heads=4, n_blocks=2, dropout=0.2,
#                        block_size=block_size)
c = Transformer2.Config(vocab_size=vocab_size, n_embd=n_embd, n_heads=4, n_blocks=2, dropout=0.2,
                       block_size=block_size)

In [5]:
for x,y in dm.train_dataloader():
    break

In [6]:
import torch
torch.manual_seed(1)
model = c.i()

In [7]:
model(x)

tensor([[[-0.5106, -0.4883, -0.2213,  ...,  0.5135,  0.6589, -0.5288],
         [ 0.0059, -0.1837,  0.1019,  ..., -0.0641, -0.6460, -0.2449],
         [ 0.0297, -0.4568, -0.3425,  ...,  0.6316, -0.0912, -0.2744],
         ...,
         [-0.4546,  0.1096,  0.4184,  ..., -0.3855, -0.5672,  0.2856],
         [ 0.0375,  0.0167,  0.5121,  ..., -0.4606, -0.8091, -0.1599],
         [ 0.3481, -0.5106, -0.6157,  ...,  0.4083,  0.6206, -0.2870]],

        [[-0.5989, -0.9339, -0.3969,  ..., -0.6836,  0.3041, -0.4241],
         [-0.5685, -0.8701,  0.0161,  ..., -0.5150, -0.5112,  0.2682],
         [ 0.1575, -0.3644,  0.5215,  ...,  0.5324, -0.6748,  0.5271],
         ...,
         [ 0.0956, -0.3694, -1.2192,  ..., -0.2393, -0.9070, -0.0547],
         [ 0.1386,  0.0098,  0.6312,  ..., -0.3457, -0.8452, -0.2361],
         [-0.0335, -0.7762, -0.1867,  ...,  0.3534,  0.3137, -0.3658]]],
       grad_fn=<ViewBackward0>)

In [30]:
x

tensor([[ 1, 50, 43,  ...,  1, 63, 53],
        [ 1, 51, 53,  ..., 51, 39, 49],
        [57,  1, 40,  ..., 59, 51, 40],
        ...,
        [42,  1, 39,  ..., 43, 57,  1],
        [ 1, 40, 43,  ..., 56, 59, 47],
        [15, 39, 54,  ..., 43,  6,  1]])

In [31]:
y

tensor([[50, 43, 39,  ..., 63, 53, 59],
        [51, 53, 56,  ..., 39, 49, 43],
        [ 1, 40, 59,  ..., 51, 40, 43],
        ...,
        [ 1, 39, 50,  ..., 57,  1, 47],
        [40, 43, 57,  ..., 59, 47, 52],
        [39, 54, 47,  ...,  6,  1, 51]])