In [24]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
from ai.datamodules.text import TextDataModule
from ai.constants import REPO_DIR
from ai.models.nlp.transformer import Transformer
from ai.misc_utils import get_vocab_size
import matplotlib.pyplot as plt
import numpy as np

In [3]:
fname = f'{REPO_DIR}/data/shakespeare.txt'
vocab_size = get_vocab_size(fname)
block_size = 256
batch_size = 2
n_embd = 32

dm = TextDataModule.Config(fname=fname, block_size=block_size, batch_size=batch_size, num_workers=0).i()

In [4]:
# c = c1 = Transformer.Config(vocab_size=vocab_size, n_embd=n_embd, n_heads=4, n_blocks=2, dropout=0.2,
#                        block_size=block_size)
c = Transformer.Config(vocab_size=vocab_size, n_embd=n_embd, n_heads=4, n_blocks=2, dropout=0.2,
                       block_size=block_size)

In [5]:
for x,y in dm.train_dataloader():
    break

In [20]:
set([set([1])])

TypeError: unhashable type: 'set'

In [13]:
x[0], x[1]

(tensor([47, 52, 45,  1, 46, 39, 52, 42,  1, 58, 46, 43, 56, 43, 47, 52,  6,  0,
         13, 52, 42,  1, 50, 39, 63,  1, 58, 46, 53, 57, 43,  1, 46, 53, 52, 53,
         59, 56, 57,  1, 53, 52,  1, 63, 53, 59, 56,  1, 46, 47, 45, 46,  1, 42,
         43, 57, 43, 56, 58, 57,  8,  0, 35, 46, 39, 58,  1, 51, 39, 63,  1, 57,
         46, 43,  1, 52, 53, 58, 12,  1, 31, 46, 43,  1, 51, 39, 63,  6,  1, 63,
         43, 39,  6,  1, 51, 39, 56, 56, 63,  6,  1, 51, 39, 63,  1, 57, 46, 43,
          7,  7,  0,  0, 30, 21, 34, 17, 30, 31, 10,  0, 35, 46, 39, 58,  6,  1,
         51, 39, 56, 56, 63,  6,  1, 51, 39, 63,  1, 57, 46, 43, 12,  0,  0, 19,
         24, 27, 33, 15, 17, 31, 32, 17, 30, 10,  0, 35, 46, 39, 58,  6,  1, 51,
         39, 56, 56, 63,  6,  1, 51, 39, 63,  1, 57, 46, 43,  2,  1, 51, 39, 56,
         56, 63,  1, 61, 47, 58, 46,  1, 39,  1, 49, 47, 52, 45,  6,  0, 13,  1,
         40, 39, 41, 46, 43, 50, 53, 56,  6,  1, 39,  1, 46, 39, 52, 42, 57, 53,
         51, 43,  1, 57, 58,

In [30]:
import torch
torch.manual_seed(1)
model = c.i()

In [31]:
model(x)

RuntimeError: No active exception to reraise

In [58]:
import numpy as np
debts = [1,2,3]
interests = [.5,.7,.3]
x = np.array([debts,
              interests])
              
i = np.argsort(interests)
x = x[:, i]

In [59]:
x

array([[3. , 1. , 2. ],
       [0.3, 0.5, 0.7]])

In [50]:
.99*np.log(1/.01)

4.559118484128211

In [51]:
.99*np.log(1/.99)

0.00994983249496649

In [31]:
y

tensor([[50, 43, 39,  ..., 63, 53, 59],
        [51, 53, 56,  ..., 39, 49, 43],
        [ 1, 40, 59,  ..., 51, 40, 43],
        ...,
        [ 1, 39, 50,  ..., 57,  1, 47],
        [40, 43, 57,  ..., 59, 47, 52],
        [39, 54, 47,  ...,  6,  1, 51]])