In [116]:
import torch
import torch.nn.functional as F
from torch import nn 
torch.manual_seed(0)
C=10
B=5
logits = torch.rand((B,10))
logits.requires_grad=True
y = torch.randint(low=0,high=4,size=(B,))
# loss = F.cross_entropy(logits,y)
y_proba = F.softmax(logits,dim=1)
loss = -torch.log(y_proba[y]).mean()
loss.backward()
loss

tensor(2.3361, grad_fn=<NegBackward0>)

In [145]:
print(logits.grad.sum(1))
logits.grad

tensor([-1.8626e-08, -3.5390e-08,  0.0000e+00, -1.6764e-08,  0.0000e+00])


tensor([[-0.0005,  0.0056, -0.0070, -0.0064, -0.0038,  0.0024, -0.0006,  0.0091,
         -0.0012,  0.0024],
        [-0.0028,  0.0003, -0.0188, -0.0122, -0.0059,  0.0077,  0.0210,  0.0298,
         -0.0126, -0.0065],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [-0.0036,  0.0107, -0.0056, -0.0041, -0.0059, -0.0075, -0.0051,  0.0107,
          0.0049,  0.0054],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000]])

In [147]:
dlogits = torch.ones_like(logits)
dlogits = torch.softmax(logits, 1)
dlogits[range(B), y] -=  1
dlogits /= B

In [152]:
# dlogits.shape

In [149]:
# dlogits

In [144]:
dlogits.sum(1)

tensor([ 1.8626e-09,  1.1176e-08,  9.3132e-10,  0.0000e+00, -3.7253e-09],
       grad_fn=<SumBackward1>)

In [131]:
dlogits

tensor([[-0.1805,  0.0256,  0.0130,  0.0136,  0.0162,  0.0224,  0.0194,  0.0291,
          0.0188,  0.0224],
        [ 0.0191, -0.1799,  0.0137,  0.0159,  0.0180,  0.0226,  0.0270,  0.0299,
          0.0158,  0.0178],
        [ 0.0221, -0.1721,  0.0166,  0.0268,  0.0170,  0.0194,  0.0290,  0.0116,
          0.0134,  0.0162],
        [ 0.0164, -0.1693,  0.0144,  0.0159,  0.0141,  0.0125,  0.0149,  0.0307,
          0.0249,  0.0254],
        [ 0.0217,  0.0163,  0.0230, -0.1868,  0.0147,  0.0163,  0.0289,  0.0283,
          0.0169,  0.0207]], grad_fn=<DivBackward0>)

tensor([-7.4506e-09, -9.3132e-09, -3.7253e-09, -1.8626e-09,  5.5879e-09])