In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
ahat = a - (a@b)/(b@b)*b
ahat, ahat@b

(array([-1.66666667,  0.        ,  1.66666667,  3.33333333]),
 8.881784197001252e-16)

In [3]:
def gram_schmidt(a):
    q = []
    for i in range(len(a)):
        
        #orthogonalization to all previous vectors
        q_tilde = a[i]
        for j in range(len(q)):
            q_tilde = q_tilde - (q[j] @ a[i])*q[j] # this works because |q[j]|==1
            
            #Test for dependennce
                
            if np.sqrt(sum(q_tilde**2)) <= 1e-10: 
                print('Vectors are linearly dependent.')
                print('GS algorithm terminates at iteration ', i+1)
                return q
                
        # Normalization
        else:
            q_tilde = q_tilde / np.sqrt(sum(q_tilde**2))
            q.append(q_tilde)
    print('Vectors are linearly independent.')
    return np.array(q).T

In [4]:
a = np.array([[-1, 1, -1, 1], 
              [-1, 3, -1, 3],
              [1, 3, 5, 7]]) 
q = gram_schmidt(a).T
print(q)
#Test orthonormality
print('Norm of q[0] :', (sum(q[0]**2))**0.5)
print('Inner product of q[0] and q[1] :', q[0] @ q[1])
print('Inner product of q[0] and q[2] :', q[0] @ q[2])
print('Norm of q[1] :', (sum(q[1]**2))**0.5)
print('Inner product of q[1] and q[2] :', q[1] @ q[2])
print('Norm of q[2] :', (sum(q[2]**2))**0.5)

Vectors are linearly independent.
[[-0.5  0.5 -0.5  0.5]
 [ 0.5  0.5  0.5  0.5]
 [-0.5 -0.5  0.5  0.5]]
Norm of q[0] : 1.0
Inner product of q[0] and q[1] : 0.0
Inner product of q[0] and q[2] : 0.0
Norm of q[1] : 1.0
Inner product of q[1] and q[2] : 0.0
Norm of q[2] : 1.0


In [21]:
A = np.array([[0,1,0,0,1],
              [1,0,1,2,0],
              [0,0,1,1,1], 
              [1,0,0,0,0],
              [0,0,0,0,3]])

def QR_factorization(A):
    Q = gram_schmidt(A)
    R = Q @ A
    return Q.T, R
Q, R = QR_factorization(A)
Q = Q.round(2)
R = R.round(2)

Vectors are linearly independent.


In [22]:
Q.T

array([[ 0.  ,  0.41, -0.5 ,  0.76,  0.  ],
       [ 0.71,  0.  , -0.5 , -0.33, -0.38],
       [ 0.  ,  0.41,  0.5 ,  0.11, -0.76],
       [ 0.  ,  0.82, -0.  , -0.44,  0.38],
       [ 0.71,  0.  ,  0.5 ,  0.33,  0.38]])

In [24]:
C = np.linalg.inv(A)
C@A

array([[ 1.00e+00,  0.00e+00,  0.00e+00,  0.00e+00,  0.00e+00],
       [ 0.00e+00,  1.00e+00,  0.00e+00,  0.00e+00,  5.55e-17],
       [ 0.00e+00,  0.00e+00,  1.00e+00,  0.00e+00,  1.11e-16],
       [ 0.00e+00,  0.00e+00,  0.00e+00,  1.00e+00, -5.55e-17],
       [ 0.00e+00,  0.00e+00,  0.00e+00,  0.00e+00,  1.00e+00]])